"""MatterLoop 供应商无关的模型协议、值对象、能力描述与注册表。"""

from matterloop_models.base import (
    ContextInputMode,
    ExactTokenCountingClient,
    MessageRole,
    ModelClient,
    ModelCompactionItem,
    ModelContextScope,
    ModelContinuation,
    ModelInputItem,
    ModelItemCategory,
    ModelItemRetention,
    ModelMessage,
    ModelMessageItem,
    ModelRequest,
    ModelResponse,
    ModelToolCallItem,
    ModelToolOutputItem,
    NativeCompactingClient,
    TokenUsage,
    ToolCall,
    ToolChoice,
    ToolDefinition,
    ToolOutput,
)
from matterloop_models.capabilities import (
    CapabilityStatus,
    ModelCapabilities,
    ModelDescriptor,
    ModelFeature,
    ModelRequirements,
)
from matterloop_models.custom import (
    CallableModelClient,
    ModelCloseCallback,
    ModelGenerateCallback,
)
from matterloop_models.errors import (
    FakeModelExhaustedError,
    ModelAlreadyRegisteredError,
    ModelAuthenticationError,
    ModelCapabilityError,
    ModelError,
    ModelInvocationError,
    ModelNotFoundError,
    ModelPaymentRequiredError,
    ModelRateLimitError,
    ModelResponseParseError,
    ModelServiceError,
)
from matterloop_models.fake import FakeModelClient, ModelResponder
from matterloop_models.registry import ModelLease, ModelRegistry, ModelRetirement

__all__ = [
    "CallableModelClient",
    "CapabilityStatus",
    "ContextInputMode",
    "ExactTokenCountingClient",
    "FakeModelClient",
    "FakeModelExhaustedError",
    "MessageRole",
    "ModelAlreadyRegisteredError",
    "ModelAuthenticationError",
    "ModelCapabilities",
    "ModelCapabilityError",
    "ModelClient",
    "ModelCloseCallback",
    "ModelCompactionItem",
    "ModelContinuation",
    "ModelContextScope",
    "ModelDescriptor",
    "ModelError",
    "ModelFeature",
    "ModelGenerateCallback",
    "ModelInputItem",
    "ModelInvocationError",
    "ModelLease",
    "ModelItemCategory",
    "ModelItemRetention",
    "ModelMessage",
    "ModelMessageItem",
    "ModelNotFoundError",
    "ModelPaymentRequiredError",
    "ModelRateLimitError",
    "ModelRegistry",
    "ModelRequest",
    "ModelRequirements",
    "ModelResponder",
    "ModelResponse",
    "ModelResponseParseError",
    "ModelRetirement",
    "ModelServiceError",
    "ModelToolCallItem",
    "ModelToolOutputItem",
    "NativeCompactingClient",
    "TokenUsage",
    "ToolCall",
    "ToolChoice",
    "ToolDefinition",
    "ToolOutput",
]
