"""MatterLoop Trace 的稳定 Span 名称与属性键。

动态角色、工具和模型信息必须写入属性，不能拼进 Span 名称。这样实时 OTel 与离线
``TraceBuilder`` 会产生同一套可查询结构，也避免高基数名称污染后端索引。
"""

INSTRUMENTATION_SCOPE = "matterloop.observability"

RUN_SPAN_NAME = "matterloop.run"
PLANNER_SPAN_NAME = "matterloop.planner"
EXECUTOR_SPAN_NAME = "matterloop.executor"
VERIFIER_SPAN_NAME = "matterloop.verifier"
COMPLETION_EVALUATOR_SPAN_NAME = "matterloop.completion_evaluator"
GENERATION_SPAN_NAME = "matterloop.generation"
TOOL_SPAN_NAME = "matterloop.tool"
TEAM_SPAN_NAME = "matterloop.team"
TEAM_AGENT_SPAN_NAME = "matterloop.team.agent"
ITERATION_SPAN_NAME = "matterloop.iteration"
VERIFICATION_SCORE_SPAN_NAME = "score:verification"

ATTR_AGENT = "matterloop.agent"
ATTR_ATTEMPT = "matterloop.attempt"
ATTR_CYCLE = "matterloop.cycle"
ATTR_EXECUTOR = "matterloop.executor"
ATTR_FEEDBACK = "matterloop.feedback"
ATTR_GOAL = "matterloop.goal"
ATTR_INPUT = "matterloop.input"
ATTR_MODEL = "matterloop.model"
ATTR_OPERATION_ID = "matterloop.operation_id"
ATTR_OUTPUT = "matterloop.output"
ATTR_PARAMETERS = "matterloop.parameters"
ATTR_RESPONSE_ID = "matterloop.response_id"
ATTR_RUN_ID = "matterloop.run_id"
ATTR_SCORE_RAW_VALUE = "matterloop.score.raw_value"
ATTR_SPAN_ID = "matterloop.span_id"
ATTR_STATUS = "matterloop.status"
ATTR_STEP_DESCRIPTION = "matterloop.step_description"
ATTR_STEP_ID = "matterloop.step_id"
ATTR_STEP_INDEX = "matterloop.step_index"
ATTR_TRACE_ID = "matterloop.trace_id"
ATTR_PARENT_SPAN_ID = "matterloop.parent_span_id"
ATTR_USAGE_PREFIX = "matterloop.usage"
ATTR_VERIFICATION_PASSED = "matterloop.verification_passed"

ATTR_TEAM_RUN_ID = "matterloop.team.run_id"
ATTR_TEAM_STATUS = "matterloop.team.status"
ATTR_TEAM_STOP_REASON = "matterloop.team.stop_reason"
ATTR_TEAM_TASK_ID = "matterloop.team.task_id"
ATTR_TEAM_TASK_OUTCOME = "matterloop.team.task.outcome"

ATTR_TOOL_NAME = "matterloop.tool.name"
ATTR_TOOL_CALL_ID = "matterloop.tool_call_id"
ATTR_TOOL_KIND = "matterloop.tool.kind"
ATTR_TOOL_OUTCOME = "matterloop.tool.outcome"
ATTR_TOOL_ARGUMENTS = "matterloop.tool.arguments"
ATTR_TOOL_ARGUMENTS_BYTES = "matterloop.tool.arguments_bytes"
ATTR_TOOL_ARGUMENTS_SHA256 = "matterloop.tool.arguments_sha256"
ATTR_TOOL_ARGUMENTS_TRUNCATED = "matterloop.tool.arguments_truncated"
ATTR_TOOL_RESULT = "matterloop.tool.result"
ATTR_TOOL_RESULT_BYTES = "matterloop.tool.result_bytes"
ATTR_TOOL_RESULT_SHA256 = "matterloop.tool.result_sha256"
ATTR_TOOL_RESULT_TRUNCATED = "matterloop.tool.result_truncated"

ATTR_SKILL_NAME = "matterloop.skill.name"
ATTR_SKILL_OPERATION = "matterloop.skill.operation"
ATTR_SKILL_SHA256 = "matterloop.skill.sha256"
ATTR_SKILL_TRUST = "matterloop.skill.trust"
ATTR_SKILL_VERSION = "matterloop.skill.version"

ATTR_MCP_CONTENT_BLOCKS = "matterloop.mcp.content_blocks"
ATTR_MCP_SERVER = "matterloop.mcp.server"
ATTR_MCP_TOOL = "matterloop.mcp.tool"
ATTR_MCP_TRUNCATED = "matterloop.mcp.truncated"

ATTR_EXCEPTION_TYPE = "exception.type"

ATTR_SCORE_COMMENT = "score.comment"
ATTR_SCORE_DATA_TYPE = "score.data_type"
ATTR_SCORE_EVIDENCE = "score.evidence"
ATTR_SCORE_NAME = "score.name"
ATTR_SCORE_SOURCE = "score.source"
ATTR_SCORE_VALUE = "score.value"
